version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mcpresso
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-this}
      - SERVER_URL=${SERVER_URL:-http://localhost:3000}
      - PORT=3000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mcpresso-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=mcpresso
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - mcpresso-network

volumes:
  postgres_data:

networks:
  mcpresso-network:
    driver: bridge 